### ISSUE TITLE
User stories and walkthrough for review

### ISSUE THREAD

**Issue by violetaria** [july2016codepathgroup2/group2#1]
### User Stories

**User onboard**
- Signup/Login 
  ![img_20160815_081923](https://cloud.githubusercontent.com/assets/8260617/17664506/8f384f18-62c2-11e6-9664-3d0dd43f6824.jpg)
- Create Profile - picture, name, location pulled from FB?
  ![img_20160815_082629](https://cloud.githubusercontent.com/assets/8260617/17664498/87657d1a-62c2-11e6-8ac5-96a9313f92e6.jpg)

![img_20160815_082637](https://cloud.githubusercontent.com/assets/8260617/17664535/c8677a20-62c2-11e6-8dbf-cc6cbfdf78a4.jpg)
- View my tasks + my profile + my messages (menu)
  ![img_20160815_082633](https://cloud.githubusercontent.com/assets/8260617/17664521/ae2ac32e-62c2-11e6-9d72-9d1df223b31b.jpg)

**Tasks**
- Publish Task
  ![img_20160815_133131](https://cloud.githubusercontent.com/assets/546242/17673072/7c544cd2-62ed-11e6-9472-80537c01edfd.jpg)
- Search for a Task (List View)
  ![img_20160815_133151](https://cloud.githubusercontent.com/assets/546242/17673084/90f83374-62ed-11e6-895a-41197528e509.jpg)
- Search for a Task (Map View)
- View Task Information
  ![img_20160815_082645](https://cloud.githubusercontent.com/assets/8260617/17664493/7dd545f0-62c2-11e6-8cbb-cb21fefa784d.jpg)
- Contact Task Owner
  ![img_20160815_133139](https://cloud.githubusercontent.com/assets/546242/17673093/9a013f7e-62ed-11e6-97d2-3d9467656d1d.jpg)
- Collect Response by Task Owner
  ![inboxmockup](https://cloud.githubusercontent.com/assets/546242/17683450/e9b57ee4-6320-11e6-8fb6-e53b4aaf328e.jpg)
- Finalize / Cancel Task
- Close/Review Task

**Comment by eddietseng** [comment]
Full mock up can be found [here](https://popapp.in/w/projects/57a9eb599dd09c5f312753e0/preview)

**Comment by nickai** [comment]
Thanks for submitting this and documenting your progress so far! Good to see you have an initial version of the wireframes complete as a starting point for your app.

Remember that by the end of your second sprint, we expect each team to have their core flows functionally complete (but rough) so this week your team should complete the first 50% of your core functionality.

While building this app, try to keep in your mind the story for your app and what you need to have a polished demo. Be aggressive about which features you can scope into the first version for internal demo day. Excited to see what your group comes up with! Let us know what we can do to help.
