### ISSUE TITLE
P1 - Create Profile and Edit Profile

### ISSUE THREAD

**Issue by violetaria** [july2016codepathgroup2/group2#6]

**Comment by eddietseng** [comment]
1. ~~Need to update user with a login counter or boolean flag. "count==1" or "first time flag == true", click profile drawer item will set to create profile fragment.~~
2. Create profile fragment.

**Comment by eddietseng** [comment]
1. Add the ability to delete skill.
2. Add the ability to click on and edit the skill
3. Add Status fragment
